circle.yml

The way we were looking for the image tag to push to dockerhub was an artifact of how were were pushing to dockerhub in our old conduit repo. The correct way is demonstrated in this commit, which smacleod has recommend and is consistent with how it is done in the [mozphab repo](https://github.com/mozilla-services/mozphab/blob/master/circle.yml#L40).
When this PR is merged it should correctly push to our DockerHub repo here [https://hub.docker.com/r/mozilla/lando-api/](https://hub.docker.com/r/mozilla/lando-api/).
This has been fixed in the lando-ui repo by [PR#3 there](https://github.com/mozilla-conduit/lando-ui/pull/3)

Fix looking up the correct image to push to dockerhub

---

landoapi/api/revisions.py
tests/canned_responses/lando_api/revisions.py

I discovered this typo while using the API to develop Lando UI. Thought I might as well fix it right away instead of writing code that depends on a typo.

 🐛 Fix typo in revisions api: date_modifed (sic)

---

docker-compose.yml
landoapi/api/revisions.py
landoapi/phabricator_client.py
landoapi/spec/swagger.yml

After a long talk with our security folks, we came to a conclusion that having every user of Lando (1000+) enter their Phabricator API keys would be a possible security risk, even if stored in a secure cookie.
This patch allows Lando to use 1 key that it owns itself to query for public revisions on behalf of users. If the user does provide an api key, that key will be used instead, which allows users who have access to secure revisions to only input their API key when needed.

Use default phabricator api key to query public revisions

---

landoapi/api/revisions.py
landoapi/spec/swagger.yml
tests/canned_responses/lando_api/revisions.py

The title of a revision is very important, but, accidentally I left it out when I initially created the revision api.

Include revision title in output of GET /revision/{id}

---

landoapi/api/revisions.py
landoapi/spec/swagger.yml
tests/canned_responses/lando_api/revisions.py
tests/canned_responses/phabricator/revisions.py

Our phabricator extensions inject the bugzilla bug id on the revisions retrieved via the api. It makes sense to pass this along through Lando API.
Also: prevent crash when Phabricator revision has no repository. Apparently, Phabricator revisions can be tied to no repository. This commit makes sure that we take that into account.

Include bug id in /revisions/{id} API response

---

landoapi/utils.py
tests/canned_responses/phabricator/revisions.py
tests/conftest.py
tests/factories.py
tests/test_dockerflow.py
tests/test_phabricator_client.py
tests/test_revisions.py
tests/utils.py

Using carefully-crafted test data fixtures can lead to brittle tests and
difficult-to-construct test scenarios in our integration tests.
Switch the test suite to use a data factory instead of static fixtures
to mock Phabricator responses.

Use data factories for testing

---

docker/Dockerfile-dev
docker/Dockerfile-prod
landoapi/wsgi.py
requirements.txt
setup.py

Run the lando-api application under uWSGI.
To build and run the production image locally add the following to `docker-compose.override.yml`:
```yaml
version: '2'
services:
lando-api:
build:
context: ./
dockerfile: ./docker/Dockerfile-prod
ports:
- "9000:9000"
environment:
- UWSGI_WORKERS=1
- UWSGI_SOCKET=:9001
- UWSGI_HTTP=:9000
```

Use uWSGI to serve the app in production

---

landoapi/api/revisions.py
landoapi/hgexportbuilder.py
landoapi/models/landing.py
landoapi/phabricator_client.py
landoapi/transplant_client.py
tests/factories.py
tests/test_hg_patch_builder.py
tests/test_landings.py
tests/test_phabricator_client.py

When requesting a landing, Construct 'hg export' formatted patches for
the Transplant service client to consume.
Todo

Send Mercurial patches to the transplant client for landing

---

tests/conftest.py

A side-effect of initializing the Alembic database schema migration
system is that it creates directories on the file system.  This
breaks the test suite in some environments and bloats test startup
time.  Since we don't need Alembic to run our acceptance tests, we
replace Alembic with a stub.

Disable Alembic migrations during testing

---

docker/Dockerfile-dev

pip won't generate scripts listed in setup.py's entry_points if the
module is already available in the PYTHONPATH.  Scripts in the dev
environment, like lando-api-dev, are not being generated as a result.
Change when we set the PYTHONPATH environment variable in the dev
environment Dockerfile so pip will generate the scripts once
again.

Fix Dockerfile-dev so it creates the lando-api-dev script

---

docker/Dockerfile-dev
docker/Dockerfile-prod

Use unbuffered stdout for all containers.  In dev this makes print()
statements work.  In prod using unbuffered output for daemons is just
plain good practice.

Use unbuffered stdout for containers

---

tests/conftest.py

The test suite is broken outside the docker environment because it
depends on the HOST_URL environment variable.  Add a mock for the
variable so the suite passes again.

Mock HOST_URL during test suite runs

---

landoapi/dockerflow.py
landoapi/phabricator_client.py
tests/conftest.py
tests/test_dockerflow.py
tests/test_phabricator_client.py

To test this change, add the following to docker-compose.override.yml:
```yaml
version: '2'
services:
lando-api:
environment:
- PHABRICATOR_URL=https://nosuchhost.test
```
and hit http://<yourdockerhostname>:8888/__heartbeat__.
The container log should output a WARNING level message.  It will not output INFO or DEBUG messages because we don't have the loggers configured for that yet (we should implement mozlogging instead).

Return HTTP 502 from failed phabricator heartbeat checks

---

landoapi/api/landings.py
landoapi/app.py
landoapi/dockerflow.py
landoapi/models/landing.py
landoapi/transplant_client.py
requirements/common.txt

Configure the application to use the mozlog structured log format for
application-level log messages (log messages from libraries and
frameworks still go through the Python Standard Library string logger).
To test, modify `docker-compose.override.yml` and set the `LOG_LEVEL` environment variable to the string value `debug`.  A message about logging initialization should appear in the container logs.  
Try setting the `LOG_LEVEL` value to `foobar` to see what happens if an unknown/typo'd log level is set.

Use mozlog for application logging

---

docker-compose.yml
landoapi/app.py
requirements/common.txt

Does what is says on the tin.  Sentry is shut off for local development.  To use it you have to give Sentry a real DSN.
I have tested this change using the lando-api Sentry project.  It reports errors correctly when they occur in a local development container.  I think we can ship this.

Use Sentry to report exceptions

---

circle.yml

Make the CircleCI build tag and push the 'latest' image tag to Docker
Hub so that we can use the latest image in the demo.

Tag the latest image in Docker Hub

---

landoapi/app.py

Remove a stale instance of the `Sentry()` object.  `initialize_sentry()` creates a local `Sentry()` instance that should be used instead of the instance removed by this PR.

Fix masked sentry variable

---

landoapi/api/revisions.py
landoapi/spec/swagger.yml
tests/canned_responses/lando_api/revisions.py
tests/canned_responses/phabricator/diffs.py

Clients sometimes need to know about the most recent diff for a revision. This change returns some metadata about the diff as well as the name and email address of the commit authors.
For example, lando-ui will use this information to allow the user to preview the final commit message allowing the user to make any final edits ahead of time.
https://trello.com/c/V3EMcEQC/445-2-return-commit-authors-in-revision-data

Add diff and commit author information in GET /revisions/{id}

---

docker-compose.yml
landoapi/api/landings.py
landoapi/models/landing.py
landoapi/spec/swagger.yml
tests/conftest.py
tests/test_landings.py

Uses API-Key header parameter to authenticate the request.
Adds TRANSPLANT_API_KEY environment variable to compare to the header.

Authenticate pingback source

---

landoapi/transplant_client.py
tests/canned_responses/lando_api/landings.py
tests/conftest.py
tests/factories.py
tests/test_landings.py
tests/utils.py

Transplant service is running via requests_mock.
This commit is removing this dependency so Lando API will be contacting
a real Transplant service.

Remove mocked transplant service

---

docker-compose.yml
landoapi/models/landing.py
tests/conftest.py
tests/test_landings.py

Currently the name of the variable is HOST_URL. This might be confused
with generic Lando API host url. The name is then changed to
PINGBACK_HOST_URL.
We also no longer need PINGBACK_PORT. It is removed.

Change the environment variable name representing the pingback url

---

landoapi/dockerflow.py

The dockerflow health and version endpoints should instruct the caller
not to cache any results. This commit sets Cache-Control to properly
disable caching.
An unused requests import is also removed as cleanup.

dockerflow: set cache-control header in responses.

---

landoapi/transplant_client.py

We had a rare event where transplant was taking *just* over 10 seconds
to complete the request from Lando. This resulted in Lando throwing a
timeout even though transplant had properly queued the request. This
change increases the read timeout specifically to allow 30 seconds.
While this shouldn't be hit often, it will hopefully save us if this
happens again.

transplant: Increase read timeout for transplant request (Bug 1542247).

---

docker-compose.yml
landoapi/api/transplants.py
landoapi/app.py
landoapi/phabricator.py
landoapi/projects.py
landoapi/tasks.py
tests/conftest.py
tests/mocks.py
tests/test_tasks.py
tests/test_transplants.py

Because Check-in Needed is being migrated to Phabricator and will be
handled by Lando, we now remove the tag from revisions when landing.
This is done asynchronously after triggering the landing so that any
errors will not block a proper response. It could have been done before
triggering the landing but any transient failure talking to transplant
would have prevented the landing even though the tag was removed.
Additionally Lando now has a `PHABRICATOR_ADMIN_API_KEY` environment
variable which is used to specify an API key for privileged actions.
This key must have access to all revisions, including those marked as
secure. Care should be taken when using this API key.
Removal of the #check-in_needed tag uses the admin api key to ensure
that it is successful for all revisions and that it …

transplants: remove #check-in_needed when landing (Bug 1535157).

---

docker-compose.yml

Pin the PostgreSQL container version to v9.6 in docker-compose.yml.  The
service dies with an error about incompatible init scripts if you try
to start the app or conduit suite with Postgres v11.

dev: pin the db container to postgres v9.6

---

landoapi/hooks.py
tests/test_hooks.py

The default error handlers eat the PhabricatorAPIException root cause
and traceback. This makes debugging API failures difficult and breaks
PyCharm unittest integration.
We can make the error handler optional in the same way that the Flask
default error handler is optional: in production it wraps all errors,
but in the test and debug environments exceptions are allowed to
propagate through the stack to make debugging easier.

app: only wrap API exceptions in production environments

---

landoapi/app.py
tests/conftest.py

Flask uses the TESTING config variable to determine if test suite errors
should propagate or be wrapped in generic HTTP status codes.  The
correct behaviour is to set TESTING=True during test suite runs.
Also killed the dead 'testing' parameter to construct_app.

tests: enable the TESTING config flag during test suite runs

---

landoapi/stacks.py
tests/test_stacks.py

In `calculate_landable_subgraphs` we iterate over the repository
values attached to the revisions in our stack and check if the
repo is valid using `repo not in landable_repos`. This blocks
the revision from landing and displays a sensible error message
about an unsupported repo.
However, in the case a repo has not been associated with a
revision, the condition will still be true as the empty value is
not in the set of landable repos. This causes confusion to end
users regarding what to do to fix the problem. In this commit we
add an extra check to assert the value of `repo` is not a
False-y value. If the value is False-y, we provide a more instructive
error message and block the revision from landing. Otherwise,
we continue with the existing block logic.

stacks: provide a more specific error message when no repo is specifed for a revision (Bug 1569721) r?smacleod

---

landoapi/transactions.py
tests/mocks.py
tests/test_transactions.py

Wrap the Phabricator API's 'transaction.search' endpoint with some
useful functions.

[sec-approval/3] client: wrap the transaction.search endpoint (bug 1553715)

---

tests/mocks.py
tests/test_revisions.py
tests/test_secapproval.py
tests/test_transplants.py

Add a PhabricatorDouble method that takes a mock object produced by
the PhabricatorDouble factory methods and returns the same object as it
would appear in a Phabricator API search result.
Refactor existing test code to use the new method.

tests: add a phabdouble helper to convert mocks to API search results

---

tests/mocks.py
tests/test_transactions.py

Allow the mocking of Phabricator comment objects, like you would have
from adding a comment to a Revision. Having comments properly mocked
makes the Transaction mocks match real Phabricator Transaction objects
more closely.

tests: mock Phabricator comments with PhabDouble

---

tests/conftest.py

Add a pytest custom assertion handler to decorate failed API responses.
In addition to reporting the failed HTTP status code the failed response 
JSON, including the error message within it, are reported in the test 
output.

tests: add detail to failed API responses in tests

---

tests/mocks.py
tests/test_transactions.py

Transaction objects can now be searched for by both PHID and by
object name, such as "D123".  This is necessary for situations where
only the object name is locally available without a network
request. It also matches the Phabricator API, which allows searches
by both PHID and object name.

tests: transactions can be searched by object name

---

landoapi/api/stacks.py
landoapi/api/transplants.py
landoapi/reviews.py
tests/test_reviews.py
tests/test_revisions.py
tests/test_transplants.py

Exclude the sec-approval team from the list of code reviewers when displaying a
commit message in the UI and when building a commit message to send to the
transplant service.  This allows the sec-approval team to consult on a change 
without revealing the security-sensitive nature of the patch in the public
commit message.

api: exclude sec-approval from the reviewers list (bug 1590225)

---

landoapi/api/transplants.py
landoapi/revisions.py
tests/test_sanitized_commit_messages.py

When a user requests landing of a commit that has an alternate commit 
message going through the sec-approval process use that alternate sanitized
commit title and commit summary as the commit's title and summary.

api: land commits using sec-approval commit messages (bug 1569209)

---

landoapi/repos.py

The conduit suite uses the repository named 'test-repo' for live testing.
test-repo was made unlandable in a prior commit.  Fix the repo name registry 
so test-repo is landable again.

repos: make test-repo landable again

---

landoapi/auth.py

The message will include instructions on how to fix an expired token
issue. Since we have different types of tokens, users can easily mix up
what to do without more specific messaging.
This change can be reverted once no more users are impacted by the recent upgrade to `flask-pyoidc`.

auth: update token expired message with meaningful instructions

---

landoapi/app.py
landoapi/cli.py

Prior to this change, all services were initialized with the same
subsystems, which causes some subsystems to stall (for example,
`RepoCloneSubsystem`) on services that don't use them and don't mount
repos. This revision adds the ability to exclude certain subsystems when
they are not needed.

Fix repo clone subsystem requirement

---

landoapi/commit_message.py
tests/test_commit_message.py

Fix that prevents Lando from mangling the reviewer names when there is a period. See https://bugzilla.mozilla.org/show_bug.cgi?id=1515217 for more info.

commit message: allow single period in nickname (bug 1515217)

---

landoapi/repos.py

Temporarily disable local transplants until bug 1648485 is landed.

repos: disable local transplants on VCT (bug 1648756)

---

landoapi/api/landing_jobs.py
landoapi/models/landing_job.py
landoapi/spec/swagger.yml
tests/test_landing_job.py

- add REST endpoint (update)
- update landing job actions enum
- add grace period functionality
See https://github.com/mozilla-conduit/lando-ui/pull/108 for UI implementation.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1503000.

landing jobs: add ability to cancel landing jobs (bug 1503000)

---

landoapi/hg.py
landoapi/repos.py
tests/conftest.py
tests/test_landings.py
tests/test_py3_codequality.py
tests/test_transplants.py

With the exception of mozilla-central, enable local transplants on all
other repos. Also, update `Repo` to use dataclasses instead of
namedtuples. This makes it easier to set defaults and improves
readability.

repos: update repos to use landing worker (bug 1651055)

---

landoapi/api/transplants.py
landoapi/repos.py
tests/conftest.py
tests/test_landings.py
tests/test_transplants.py

This change will enable Landing Worker (and ability to cancel landing jobs) on `mozilla-central`. Note that `mozilla-central` also needs to be added to the `REPOS_TO_LAND` environment variable upon deployment.
Also:
- Rename `transplant_locally` to `legacy_transplant`
- Change default value of `legacy_transplant` to `False` (i.e. a repo will use the landing worker by default)

repos: enable landing worker for mozilla-central (bug 1652795)

---

landoapi/landing_worker.py

In certain cases, the enabled repos are not correctly refreshed which
can cause landing jobs to be stuck in a pending state until the repos
are refreshed. This change forces a recheck periodically whenever the
list of enabled repos does not match the applicable repos.

landing worker: refresh enabled repos more frequently (bug 1655546)

---

landoapi/hg.py

If a push race fails, a `CommandError` exception is raised, but the landing worker is trying to catch a `LostPushRace` exception. Fix this so that if a push race is detected, the `LostPushRace` exception is raised, instead of a generic `CommandError`.

hg: reraise custom defined exception (bug 1656239)

---

landoapi/api/stacks.py
landoapi/api/transplants.py
landoapi/commit_message.py
landoapi/repos.py
landoapi/spec/swagger.yml
tests/conftest.py
tests/test_commit_message.py
tests/test_transplants.py

The API should accept a flags parameter when submitting a transplant, and allowed flags should be appended to commit messages.

stacks: add support for DONTBUILD flag (bug 1642939)

---

landoapi/api/transplants.py
landoapi/commit_message.py
landoapi/models/landing_job.py
landoapi/repos.py
tests/conftest.py
tests/test_commit_message.py

commit message: don't duplicate flag if already present (bug 1661134)
transplants: add help text to flags (bug 1658019)

transplants: fixes to DONTBUILD (bug 1661134, 1658019)

---

landoapi/api/transplants.py
landoapi/projects.py
landoapi/revisions.py
landoapi/transplants.py
tests/mocks.py
tests/test_revisions.py

Adds support for testing policy tags by:
- Checking if a repository has a `testing-policy` project associated with it, thus implying that said repo should enforce testing policy tags on all revisions
- Checking if a particular revision has a testing policy tag, and if not, adds a warning to the revision

transplants: add support for testing policy warnings (bug 1666309)

---

landoapi/app.py
tests/test_health.py

The [__heartbeat__](https://api.lando.services.mozilla.com/__heartbeat__ ) endpoint currently fails in production, because Transplant has been decomissioned. This fixes the health check.

app: remove transplant from health check (bug 1691707)

---

landoapi/api/landing_jobs.py
landoapi/spec/swagger.yml

Add an API endpoint to check average duration, counts, and number of
attempts of landings given a date range.

landing jobs: add stats endpoint (bug 1695047)

---

landoapi/hg.py
landoapi/landing_worker.py
tests/test_landings.py

- copy reject files in subdirectories
- handle deleted files that no longer exist
- improve parsing of rej paths

landing worker: fix parsing of rejects (bug 1695350)

---

landoapi/landing_worker.py
tests/test_landings.py

- do not fetch failed paths form raw output
- look at .rej paths instead
- trim last 4 characters instead of using .rstrip to get file path

landing worker: fix failed paths parsing (bug 1696396)

---

landoapi/transplants.py
tests/test_transplants.py

Adds a revision warning to assert a revision does not have `WIP:`
as the beginning of it's revision title. The presence of `WIP:`
indicates a work-in-progress revision and should be scrubbed before
landing by the user.
We could follow up with some code to automatically scrub the `WIP`
text from the commit message, but this is a good start for now.

Bug 1749754: add a landing warning to check if a patch has `WIP:` in the title

---

landoapi/reviews.py
landoapi/transplants.py
tests/test_landings.py

Lando makes use of enums to compare allowed values,
and is inconsistent about using `==` or `is` to
make these comparisons. Convert uses of `is` enum
comparisons to `==` wholesale.
Checked by doing a global search for all `@enum`
in the repo, then searching for all instances of
each class type and ensuring comparisons are made
with `==`.

Bug 1754801: compare enum equality with `==` consistently

---

landoapi/treestatus.py
tests/test_treestatus.py

Within the new uplift workflow, repositories on Lando with
"approval required" status should be considered open for landing.
The approval is checked in Lando by asserting `release-managers`
review on the revision and the hg hook asserts `a=<reviewer>` is
present in the first line of the commit message. Thus we can
consider an "approval required" repo as landable and enabled.

treestatus: consider "approval required" status as open for landing (Bug 1756036)

---

landoapi/api/stacks.py
landoapi/api/transplants.py
landoapi/reviews.py
tests/test_revisions.py

Fixes a regression caused by #180 where all RelMan reviews are
rewritten from `r=reviewer` to `a=reviewer`. This should only
occur on an uplift repository, so we amend usages of
`approvals_for_commit_message` to only apply when this flag is
set.
Some of the secure revision tests fail after this change due to
a missing repository tagged on the revision so we add a repo to
these tests.

approvals: only rewrite RelMan reviews as `a=` for approval required repositories (Bug 1755932)

---

landoapi/repos.py

PyRight is showing errors in my editor as the value of
`commit_flags` defaults to `None` but the type should
only be a list of tuples. Use the `field` function to
define a default factory for the value, resulting in
a consistent type definition for the fields.

repos: fix typing issue for `repos.commit_flags` (Bug 1759890)

---

landoapi/hg.py
landoapi/hgexports.py

Set the concrete `Optional[str]` type for `PatchHelper.header`
and add a `None` check where one is required.

hgexports: clarify `PatchHelper.header()` has type `Optional[str]` (Bug 1759890)

---

.circleci/config.yml

`circleci/` convenience images are deprecated in favour of the
`cimg/` namespace. Switch to them, and use the `3.9` tagged image
while we are here.

ci: move convenience images to `cimg` Docker namespace (Bug 1762457)

---

landoapi/hg.py

Noticed the TODO mentioning we should use a template. Even
easier is to add `--id` to the call to `hg id` which will
cause only the 12-character changeset hash to be returned.

hg: add `--id` to `hg id` call so output can be used directly

---

tests/test_hg.py

We have a test for an upstream Mercurial bug that is skipped on
any non-5.1 Mercurial. Remove the skip to force the test to always
run. This is likely a leftover from importing autoland transplant
into Lando.

testing: do not skip patching test on any version of Mercurial

---

landoapi/api/transplants.py
landoapi/api/uplift.py
landoapi/spec/swagger.yml
landoapi/stacks.py
landoapi/transplants.py
landoapi/uplift.py
landoapi/validation.py
tests/mocks.py
tests/test_uplift.py

Remove code related to "approval requests" from the uplift endpoint.
Add `move_drev_to_original` from moz-phab to keep summary consistent.
Change the incorrect `commit` key on the diff to the correct
`rev` key to fix the endpoint. Add some type hints to various pieces
of code.

uplift: fix endpoint and add support for stack uplifts (Bug 1764213)

---

landoapi/uplift.py
requirements.in
tests/test_uplift.py

The regex used to parse the major milestone version failed
on the content of the current beta (which is now in the tree
as a test case as `MILESTONE_TEST_CONTENTS_2`). This commit
changes the parsing to instead take the last line of the file
and pass to a `Version` object, which is returned from the
parsing function.

uplift: use `packaging.version.Version` to handle milestone version parsing (Bug 1788078)

---

landoapi/landing_worker.py
landoapi/repos.py
landoapi/tasks.py
requirements.in
requirements.txt
tests/test_landings.py

Adds a call to Phabricator's `diffusion.looksoon` API to trigger
syncing from the upstream repo. This should cause revisions
to close faster, especially on uplift repositories.
As part of this patch some tests were failing due to out of date
`moto` conflicting with `responses`. Upgrading `moto` caused the
removal of several packages that are used directly in testing and
the main application. These packages are added to `requirements.in`
so they are explicit dependencies.

phabricator: call `diffusion.looksoon` on landing to trigger repo sync (Bug 1455468, Bug 1788722)

---

landoapi/landing_worker.py

The default value for `sleep_seconds` is an
`int`, but elsewhere in the codebase we pass values
for `sleep_seconds` as a `float`. Change the default
value to a `float` as well to avoid type checker errors.

landing_worker: make `sleep_seconds` a float (Bug 1759890)

---

landoapi/hg.py
tests/test_landings.py

The output can be littered with irrelevant information, leading
to overly verbose commit messages that don't work well with
Git/Hg etc.

autoformat: stop adding `mach lint` output to commit message (Bug 1802406)

---

landoapi/api/diff_warnings.py

There is a missing comma which causes two lines to be joined
into one by Python. These two lines should each be their own
argument. Add a comma to fix this problem.

diff_warnings: add comma so each line is a different argument (Bug 1802553)

---

landoapi/auth.py

The `scopes` type is set to `tuple[str]`, which implies to type
checkers that the type is always a single `str` element tuple.
Since we are passing `tuple`'s of different length in various
places, it is more appropriate for the type to be `Iterable`,
which also aligns with the docstring comment about `scopes`.
Use the `Iterable` from `collections.abc` as that is the
preferred way in Python 3.9+.

typing: set `scopes` type to `Iterable` (Bug 1759890)

---

landoapi/hg.py
landoapi/landing_worker.py
landoapi/models/landing_job.py

Add a field to `AutoformattingException` that contains relevant details
for display in failure emails.
Also add type hints to `transition_status` while we are here.

autoformatting: add a details field to `AutoformattingException` and populate with mach output (Bug 1803169)

---

landoapi/api/uplift.py
landoapi/commit_message.py
landoapi/revisions.py
landoapi/transplants.py
landoapi/uplift.py
tests/test_commit_message.py

- Add type hints and clarify `convert_path_id_to_phid`.
- Split landing_path into two variables with different types.
- Add type hints for gather_involved_phids.
- Add type hint to get_uplift_request_form.
- Add type hints for get_bugzilla_bug.
- Make format_commit_message type correct everywhere.

typing: add hints and clarify types in various places (Bug 1759890)

---

landoapi/commit_message.py
landoapi/hg.py
landoapi/landing_worker.py
landoapi/uplift.py
tests/test_commit_message.py
tests/test_landings.py

Instead of having `No bug` in the commit message title,
use the bug numbers from all changesets in the stack.
Move collection of stack changeset titles earlier in
the job processing and parse bug IDs at the landing
job level, passing the ids into the formatting function
as well as into the uplift code where they were previously
parsed. Add a function `bug_list_to_commit_string` to
convert these bug IDs into an appropriate bug string
and add this string to the autoformat commit message
template. Update the test commit messages with a bug
number to ensure the parsing is correct.

autoformat: add bug numbers to autoformat commit messages (Bug 1802558)

---

landoapi/api/diff_warnings.py
landoapi/api/revisions.py
landoapi/api/stacks.py
landoapi/api/transplants.py
landoapi/api/uplift.py
landoapi/decorators.py
landoapi/revisions.py
landoapi/transplants.py
tests/test_decorators.py
tests/test_revisions.py

Move the `PhabricatorClient` from `g.phabricator` to an argument
passed to the necessary API function. This makes cases where
we require Phabricator more explicit and removes the global
`g.phabricator`, which was inconsistently defined and typed.
In making this change we also notice the `get_phabricator_repo`
usage and function is unnecessary as we have already retrieved
the required `repo` information from Phabricator when the function
is called.
Also rename some variables where we convert between types to
keep each variable name consistently typed.

phabricator: remove `g.phabricator` and replace with arguments to command function (Bug 1759890)

---

landoapi/api/landing_jobs.py
landoapi/commit_message.py
landoapi/landing_worker.py
landoapi/models/landing_job.py
landoapi/phabricator_patch.py
landoapi/projects.py
landoapi/revisions.py
landoapi/stacks.py

- Add type hints to some functions in `revisions.py`.
- Add type hints to `get_project_phid`.
- Make `flags` kwarg an `Optional`.
- Make `action` a `LandingJobAction` instead of a `str`.
- Remove `diff_id` from base exception handling as it is irrelevant, may be unbound.
- Add `dict` type for list elements in `patch_to_changes`.
- Use a different variable name than `f`, add docstring.
- Add a docstring for `serialize_hunk`.
- Add type hints for `RevisionStack` constructor.
- Fix types for `RevisionStack`.
- Use new variable name for start/end datetimes.

typing: add/clarify type hints in several places (Bug 1759890)

---

landoapi/api/stacks.py

We are already iterating over a dict where each key is the PHID,
so there is no need to pull the PHID from the revision object.

stacks: use phid from stack_data instead of pulling from revision

---

landoapi/uplift.py
tests/test_uplift.py

The `summary` field in Phabricator does not include the
`Differential Revision` line, so `move_drev_to_original`
effectively does nothing. Instead place the value of
`revision.fields.uri` in the summary as `Original Revision`
directly.

uplift: remove `move_drev_to_original` and instead place line directly from `revision.fields.uri` (Bug 1804508)

---

landoapi/api/uplift.py
landoapi/spec/swagger.yml
landoapi/stacks.py
landoapi/uplift.py
tests/test_stacks.py

Change the swagger schema for the uplift endpoint to take
a revision ID instead of a landing path. Add simple stack
walking methods to `RevisionStack` and make `get_uplift_conduit_state`
return a `RevisionStack`. Use these stack walking methods in
place of the passed `landing_path` to determine the order
in which to create uplift revisions.

uplift: stop using a `landing_path` for uplift endpoint (Bug 1801926)

---

landoapi/uplift.py
tests/test_uplift.py

`create_uplift_revision` requires the revision to have a bug
ID present in the `bugzilla.bug-id` field. Add a check to
`get_uplift_conduit_state` to assert each revision being uplifted
is associated with a bug.

uplift: add check for bug IDs to get_uplift_conduit_state (Bug 1804506)

---

landoapi/commit_message.py
tests/test_commit_message.py

Remove the conservative `R_SPECIFIER` and replace with `SPECIFIER`
everywhere. This expands the values used for review specifiers
to catch and scrub `a=` and others when landing code.

commit-message: expand instances of review specifiers (Bug 1756048)

---

landoapi/stacks.py
tests/mocks.py
tests/test_stacks.py

In https://github.com/mozilla-conduit/lando-api/pull/236 I removed an
unnecessary call to `diffusion.repository.search` as we were already doing
a search for the same repo earlier in the program logic and passing the
returned object into the check. After removing and deploying this call,
Lando started failing when trying to access the projects attachment on
the repo object. This is because the call to `diffusion.repository.search`
doesn't include the projects attachment parameter.
We need to add `projects: True` to the `diffusion.repository.search` call
so the projects data is available.

stacks: attach `projects` for repos in `request_extended_revision_data` (Bug 1805265)

---

landoapi/api/uplift.py

Repos are mapped by "shortName: Repo()" in `repos.py` and
thus the value we need to return from the `GET` endpoint
is the `shortName`.

uplift: return repo `shortName` instead of `name` (Bug 1805695)

---

landoapi/api/stacks.py
landoapi/api/transplants.py
landoapi/projects.py
landoapi/uplift.py
tests/test_transplants.py

In a few places within Lando-API we retrieve the `#release-managers`
group information. In some cases we only require a PHID and in some
cases we need the entire group information. When we need each, we
make a call to the Conduit API to get the required info.
Consolidate these two use cases into one function that returns all
information for the `release-managers` project, eliminating the extra
calls to Conduit. Move `get_release_managers` to `projects.py` where
it makes more sense and cache it for efficiency.
Add the `release_management_project` fixture to `test_transplants.py`
tests where it is needed.

projects: remove `get_relman_phid` in favor of `get_release_managers` (Bug 1806455)

---

landoapi/api/transplants.py

`_lock_table_for` takes either a model or a table name and has
logic to check that only one is passed. However we only ever pass
a model in practice, and if a table name was passed the function
would throw an exception anyways.

transplants: simplify `_lock_table_for` (Bug 1807954)

---

landoapi/api/stacks.py
landoapi/api/transplants.py
landoapi/phabricator.py
landoapi/reviews.py
landoapi/stacks.py
tests/test_revisions.py
tests/test_sanitized_commit_messages.py
tests/test_stacks.py

- Pass `landable_repos` as a `set` instead of a `dict`.
- Add types for `result_list_to_phid_dict`.
- Fix types for some functions in `reviewer_identity`.
- Add a `None` check for `sec_approval_project_phid` and add
add sec-approval project to tests where it is needed.

typing: fix a few typing issues (Bug 1759890)

---

landoapi/transactions.py
tests/test_transactions.py

Remove `get_raw_comments` as it is an unused function.
While we're here also add type hints to the other functions
in this file.

transactions: remove unused `get_raw_comments` (Bug 1809730)

---

landoapi/api/transplants.py
landoapi/models/revisions.py
landoapi/transactions.py
landoapi/transplants.py
tests/mocks.py
tests/test_transactions.py
tests/test_transplants.py

[Bug 1504720 - Require confirmation when a revision has unresolved comments](https://bugzilla.mozilla.org/show_bug.cgi?id=1504720)
- right now if a revision has unresolved comments in the stack, that information is not surfaced to the user
- adds a warning which will check the transactions for the revisions in `to_land` and determine if any of the inline comments are still unresolved

transplants: add warning for revisions with unresolved comments (Bug 1504720)

---

landoapi/auth.py
landoapi/commit_message.py
landoapi/hg.py
landoapi/projects.py
landoapi/reviews.py
landoapi/stacks.py
landoapi/uplift.py

Since we are on modern Python we can use builtins
for type hints. Also remove usages of `Union`
in favor of separating values with `|`.

typing: remove `typing.{Dict,List,Set,Tuple,Union}` and use builtins directly (Bug 1759890)

---

landoapi/auth.py
landoapi/cli.py

We don't need the `Type` specifier for `get_subsystems`,
we can just use `Subsystem`. Also add a return type for
the function.
Add types where they are missing from `auth.py`.

typing: add missing types to `auth.py` and `cli.py` (Bug 1759890)

---

landoapi/api/landing_jobs.py
landoapi/api/landings.py
landoapi/decorators.py
landoapi/models/base.py
landoapi/models/configuration.py
landoapi/models/landing_job.py
landoapi/models/secapproval.py
landoapi/models/transplant.py

Finish adding type hints to all modules in `api/` and `models/`.
Type hints for `put` are updated from `int` to `str` to reflect
the correct state in `swagger.yml`.
Add a type alias for configuration values that is an alias to
`bool | int | str`. Also raise at the end of the function to
avoid an accidental `None` return in some edge cases.
Convert `ConfigurationKey` to a proper `Enum` type, add
type hints for it and convert usages of it's underlying `str`
to use the `.value` attribute.
Add `flask_sqlalchemy.BaseQuery` as the return type for
model queries.

api, models: finish adding type hints, make `ConfigurationKey` a proper enum (Bug 1759890)

---

landoapi/commit_message.py
tests/test_commit_message.py

You can see an example of the problem at https://hg.mozilla.org/mozilla-central/rev/1b3d211c35998c7a277d40b8a01c242e45a1223a
Previously the commit message would be like "Bug 1790368, 1790368, 1790368: apply code formatting via Lando".

autoformat: deduplicate bug IDs in commit message (Bug 1808090)

---

landoapi/uplift.py

Technically this can be `None`, so we should check
it to avoid problems down the line.

uplift: check `target_repo` for `None` (Bug 1759890)

---

landoapi/landing_worker.py

Noticed this lingering usage of a `str` during testing.

landing_worker: use `ConfigurationKey` instead of string variable (Bug 1759890)

---

landoapi/secapproval.py
landoapi/sentry.py
landoapi/transplant_client.py

Also rename `phabclient` to `phab` to match the usual Lando convention.

types: add type hints to `secapproval.py`, `sentry.py`, `transplant_client.py` (Bug 1759890)

---

landoapi/api/transplants.py
landoapi/projects.py

Add an `Optional` type around `get_release_managers`, since it
returns the value of `phab.single` which is not confirmed to
exist. Add a `None`-check to locations where we assume it is
available.
While we're here also add a type hint to `project_search` as
it is missing one.

projects: clarify that `get_release_managers` returns an `Optional` (Bug 1759890)

---

landoapi/repos.py
landoapi/uplift.py
landoapi/workers/landing_worker.py
tests/test_uplift.py

The status tracking flags for ESR differ slightly from beta and release.
Make the tracking flag configurable per-repo instead of hard-coded to
a specific format. On the Bugzilla side the uplift API endpoint allows
changing any `cf_status_*` flag.

uplift: make Bugzilla status tracking flag configurable per-repo (Bug 1825091)

---

landoapi/phabricator_patch.py

While trying to determine if we had a bug in the
code that converts a Phabricator diff into a format
that is usable for uploading as a Phabricator revision
I found some areas that could be cleaned up in
`phabricator_patch.py`.
Move building the `news` and `olds` lists into the
main loop. Remove brackets around the variable names
in the for loop. Add periods to comments for some
consistency. Add docstrings to enums where appropriate.
Create an enum for diff operations and use it in the
diff parsing logic.

phabricator: cleanup some of the patch parsing code

---

landoapi/auth.py

Change `scopes` from a keyword argument to a positional argument,
indicating that scopes must be passed to the decorator. The keyword
argument syntax of `scopes=` still works for positional arguments
so no other changes are required and the purpose of the argument
is still clear when reading usages of the decorator.

auth: make `scopes` a required argument in `require_auth0` decorator (Bug 1832362)

---

landoapi/hgexports.py
landoapi/models/revisions.py

While testing the try API endpoint I noticed my very simple
patch was failing to apply. This is because the type hint for
`Revision.set_patch` is incorrect and the raw diff returned
from Phabricator is actually a `str`, not `bytes`, and thus the
type I was using was incorrect. The timestamp is also a `str`
and not an `int`. Update the function signature to match reality,
and while we're here add type hints to all of `hgexports.py`.

typing: add types to `hgexports.py` and fix `set_patch` types (Bug 1759890)

---

landoapi/hgexports.py

Refactor some patch parsing code in the `HgPatchHelper` to
clarify what is taking place. Use `enumerate` instead of a
manually incremented looping variable. Flatten if-statement
logic to reduce repeated behaviour and add a comment describing
what is taking place within the loop.

hgexports: refactor patch parsing code (Bug 1846330)

---

landoapi/uplift.py
tests/test_uplift.py

Adds a `strip_depends_on_from_commit_message` function that removes
`Depends on` lines from commit messages. Pass the commit message
of the original revision through this function before creating the
uplift revision to avoid linking uplift revisions to the original
revision.

uplift: strip `Depends on` text from commit message (Bug 1850387)

---

landoapi/hg.py
landoapi/workers/landing_worker.py
tests/test_hg.py

When pushes fail due to timeouts waiting for the repo lock,
Lando should wait and retry the push. Add a new exception for
this condition that includes snippets of the expected output
from Mercurial, and add the exception to the block of temporary
failure exceptions when trying to push.

hg: retry after Mercurial repo lock waiting timeouts (Bug 1853965)

---

landoapi/hgexports.py
tests/test_landings.py

Remove the buffer read size argument from calls to `BytesIO.read`
to instead read to EOF. Parametrize the integrated landing job
with a test case that would fail on the current behaviour due
to an improperly decoded string.

hgexports: read buffer to EOF instead of in chunks (Bug 1855328)

---

landoapi/api/try_push.py
landoapi/hg.py
landoapi/hgexports.py
landoapi/models/revisions.py
landoapi/workers/landing_worker.py
tests/test_hg.py
tests/test_hgexports.py
tests/test_landings.py
tests/test_transplants.py

Transition from using `io.BytesIO` to `io.StringIO` for content buffers.
Update uses of `NamedTemporaryFile` to open in `w+` mode with a specified
encoding.

landings: use `StringIO` instead of `BytesIO` everywhere (Bug 1855328)

---

landoapi/hg.py
landoapi/workers/landing_worker.py
tests/test_hg.py

Add a `PullFailureException` with a snippet that looks for errors
during `hg pull` and add it to the list of Lando exceptions
that can be raised from an hglib exception. Add an except
case to the `update_repo` try block that is similar to the case
in the `push` try block, to allow the job to be retried when this
exception is encountered.

hg: add a `PullFailureException` to retry landings after a 500 during pull (Bug 1858500)

---

landoapi/hg.py
landoapi/workers/landing_worker.py
tests/test_hg.py

The error snippet for `PullFailureException` is a piece of text that
comes from Lando, not Mercurial. The correct piece of text to look
for is `abort: HTTP Error 500`, which is a more general error that
can happen when load on hg is high.
Rename `PullFailureException` to `HgmoInternalServerError` and update
the snippet to reflect the output from hg. Since this error is more
general, we also add it to the set of exceptions to consider a temporary
failure at push time.

hg: change `PullFailureException` to `HgmoInternalServerError` (Bug 1860067)

---

docker-compose.yml

Add `--upgrade` to the `pip-compile` command in our `build-requirements`
docker-compose recipe so packages are upgraded to later versions when possible.

docker: add `--upgrade` to `pip-compile` command (Bug 1824007)

---

landoapi/api/uplift.py
landoapi/uplift.py

Add the `metrics` attachment to the Conduit API call for the target
repo, which adds the most recent commit hash from that repo to the
returned data. Use this commit hash as the `sourceControlBaseRevision`
value when uploading the diff to Phabricator. This mirrors how the
value is set in `moz-phab`. This fixes the mangled diff appearance
on Phabricator, and will fix the code review bot runs on uplift
revisions.

uplift: set `sourceControlBaseRevision` as latest commit on target repo (Bug 1843041)

---

landoapi/models/landing_job.py

Add a type hint for `LandingJob.revisions`. This fixes LSP features on this field,
which don't work at the moment as the LSP can't infer the type from SQLAlchemy's
string-based type hints.

landing-job: add a type hint to `revisions` (Bug 1759890)

---

landoapi/hgexports.py
tests/test_hgexports.py

When empty Git commits are sent to Lando in `git format-patch`
format, Lando fails to parse the commit correctly. Currently
Lando will fail to find the `---` line used to separate the
commit message from the diff, and assume all lines in the
patch body are part of the commit message. The parsing will
then fail later down the line as Lando will not find a valid
diff line in the body.
Add an `else` clause to the loop which looks for the `---` line
separating the extended commit message and the diff, which when
reached indicates that no diff is present on the commit. In this
case we strip the last two lines of the gathered commit message
and return an empty diff. Add a test for parsing a patch generated
from an empty commit to `test_hgexports.py`.

hgexports: empty Git commits aren't parsed correctly (Bug 1867036)

---

landoapi/api/uplift.py
landoapi/phabricator_patch.py
landoapi/uplift.py
tests/test_phabricator_patch.py
tests/test_uplift.py

Extend `get_uplift_conduit_state` to also query `differential.querydiffs`
and return all known diffs associated with the selected uplift
revisions. When creating the uplift revisions, add a function to
parse through the diffs and return the latest diff that does not
have a `creationMethod` of `commit`. This works around an issue
in Phabricator where diffs are created with empty binary files
when a new diff is created after parsing a commit from the observed
version control repository.

uplifts: query `differential.querydiffs` to find the latest non-`commit` diff (Bug 1709608)

---

.circleci/config.yml

Using CIRCLE_TAG in development and staging image tags to build immutable tags for deployment.

fix(circleci): Using CIRCLE_TAG in develop and stage image tags (bug 1870070)

---

.circleci/config.yml

`CIRCLE_TAG` is not populated when we want to create dev and stage images.
Using `CIRCLE_SHA1` instead of `CIRCLE_TAG` for dev and stage tag names

fix: Using SHA1 in dev/stage image name instead of tag

---

tests/test_transplants.py

While debugging bug 1871425 we orignally had a suspicion that
the issue was resulting from Lando erroneously applying later
patches in the stack when it should only have applied the
requested patches. I noticed we don't have a test for this
case, so I added one myself, and it passed as expected. We
might as well keep this simple test around just to provide
extra test coverage of this use case.

testing: add test for partial stack request

---

landoapi/hg.py

Add the `--verbose` flag to the `mach lint` call so more information
is displayed in log output when linters fail.

autoformat: run linters with `--verbose` (Bug 1871425)

---

landoapi/hgexports.py
tests/test_hgexports.py

Some patches sent with Git will include whitespace at the end of the
patch, meaning the Git version info is the last 3 lines instead of
2. Add a function which scans the lines in reverse and looks for
the first line beginning with `--` instead of using a naive slice
that removes the last two lines of output.
Update the Git parsing test to include extra lines of whitespace
to account for this change in the main tests for `GitPatchParser`.
Also add a simple test for the new parsing function.

git: scan end of patch for `--` instead of assuming last two lines (Bug 1856590)

---

landoapi/transplants.py

Also rename the `r` variable to `reviewers` while we are here.

transplants: use `values()` instead of `items()` since key is unused

---

landoapi/hg.py
tests/test_hg.py

In bug 1864463 we added a snippet so pushlog operational failures in
hgmo resulted in a retry instead of a permanent failure of the landing
job. The snippet we check for was the very generic `abort: push failed
on remote`, which is actually an error message seen for many other
failures, including problems with the patch that will always cause
the push to be rejected.
Remove the generic snippet and replace with a more specific error about
pushlog operational failures.

hg: change push failure snippet to be more pushlog specific (Bug 1877451)

---

landoapi/transplants.py
tests/conftest.py

`transplants.py` has a function for comparing the equality of two
confirmation tokens that is a simple wrapper around `==` to allow
for easy replication of unequal tokens in test conditions. However,
the pytext fixture which is hooked into this shim is unused. Remove
the shim and replace the function with a simple `==` comparison.

transplants: remove unused token comparison mocking shim

---

landoapi/api/stacks.py
landoapi/api/transplants.py
landoapi/projects.py
landoapi/revisions.py
landoapi/transplants.py
tests/conftest.py
tests/test_reviews.py
tests/test_revisions.py
tests/test_sanitized_commit_messages.py
tests/test_stacks.py
tests/test_transplants.py
tests/test_uplift.py

Add a blocking check that enforces revisions with the `needs-data-classification`
tag cannot land. The check is similar to the testing policy project tag checks
except it simply looks for the `needs-data-classification` tag and
blocks landing if it is present on the revision. The tag requires the
PHID of the project tag so it is generated with a factory function in a
similar manner to the release manager approval blocking check.

revisions: block revisions with `needs-data-classification` tag from landing (Bug 1880861)

---

tests/test_transplants.py

In the list comprehension where we set `job.revision_order` in
`create_landing_job_with_no_linked_revisions`, we iterate over
`revisions` and set the iteration variable as `r`, but the
value that ends up in the list uses the leftover `revision`
variable from the loop iteration above. Rename `r` to `revision`
so the correct variable is used.

tests: use correct loop variable and rename to `revision`

---

landoapi/repos.py

Add the existing `large-repo` Phabricator repo to Lando so patches can
be landed there for testing.

repos: add `large-repo` to dev repo configs (Bug 1821153)

---

tests/test_transplants.py

Make `landing_state` a separate argument in `create_state`, so callers
who want to create a custom landing state must do so with
`create_landing_state` directly instead of indirectly via
`create_state`.

testing: split `create_landing_state` into a separate kwarg of `create_state` (Bug 1895933)

---

landoapi/cli.py

This command was a one-off to import data into Lando from
RelEng Treestatus. It should be removed to avoid being run
again.

commands: remove `import-treestatus` command (Bug 1894984)

---

landoapi/hg.py

Our current snippet parsing for `hg push` output looks for `is CLOSED`
to determine if a tree is closed. When the Treestatus API returns an
error, it will instead print that it is `treating as if CLOSED`. Since
we don't check for that specific string we can sometimes treat closures
as permanent failures. Add a snippet to account for this tree-closed
state.

hg: add a snippet to consider Treestatus API failures as closed (Bug 1896696)

---

landoapi/repos.py
tests/conftest.py
tests/test_transplants.py

There is a test repo `uplift-target` used in some tests that is
added to the `local-dev` repo config. In reality this repo should
be present in the mocked out testing-only `test` repo config. Move
this test repo to the correct location and update tests with fixtures
to make the repo available.

testing: move `uplift-target` repo to mocked repo config (Bug 1896501)

---

landoapi/api/stacks.py
landoapi/api/transplants.py
landoapi/transplants.py
tests/test_stacks.py

The `assess_stack_state` function is doing two things at the same time.
Firstly, it is creating the `StackAssessmentState` from some arguments.
Then, it runs the checks against the state and returns a `StackAssessment`.
Split the `assess_stack_state` function into a function that returns a
`StackAssessmentState`, and have callers call `run_landing_checks`
directly. This will enable us to move the `create_state` function into
a proper fixture in a later PR.

checks: split `assess_stack_state` into a state builder and check runner (Bug 1896501)

---

tests/conftest.py
tests/test_transplants.py

Redefine `create_state` as a pytest fixture built with existing
fixtures and proper Lando internals. This brings the state used
in the tests post-refactor more in line with our existing test
infrastructure.

testing: defined `create_state` as a test fixture built with Lando internals (Bug 1896501)

---

landoapi/hooks.py

Add an exception for the Treestatus API endpoints to the
maintenance mode hook. Unlike the dockerflow endpoints, the
Treestatus endpoints are defined with Connexion, and the
derived value of `request.endpoint` ends up being an underscore
separated represenation of the function namespace. Add a check
to exclude any endpoints that are within that namespace.

hooks: exclude treestatus API endpoints from maintenance mode (Bug 1896696)

---

landoapi/transplants.py

Similar to the logic for blocking checks, only add revision warnings
to the assessment if the PHID in question is in the relevant assessment
set. I noticed that warnings for successor revisions were appearing when
trying to land only part of a stack, which this PR resolves.

checks: only apply warnings to assessments for relevant PHIDs (Bug 1897007)

---

landoapi/transplants.py
tests/test_transplants.py

Add a blocking check that asserts the `try_task_config.json` file is not
introduced erroneously to a non-try repo.

checks: add a check to reject `try_task_config.json` outside of `try` (Bug 1895931)

---

landoapi/api/try_push.py
landoapi/hgexports.py
landoapi/transplants.py
tests/test_try.py

Add a `DiffAssessor` class as an internal API for running
diff-based checks. Move existing diff-inspecting checks
into the API and update landing checks to use them. Add
a `run_diff_checks` method which runs each check and
returns a list of string errors for display on failure.
Hook the `run_diff_checks` API into the try push revision
building function, so the currently ported checks are
run on try pushes. Add integration tests to show that
pushes are accepted/rejected as appropriate based on
these diff checks.
Since some checks will require inspection of the landing
repo to determine if the check is valid, we add a
`get_repo_for_revision` method that returns the repo for
a revision based on the passed `revision` Phabricator API
object. The logic is derived from the uplift blocking
check …

hooks: add a diff inspection API for landings and try pushes (Bug 1899584)

---

landoapi/api/try_push.py
landoapi/commit_message.py
landoapi/hgexports.py
tests/test_hgexports.py

Port the commit message validation hook from hgmo into a Lando
`DiffAssessor` check. Most of the code and accompanying regexes
are ported directly from version-control-tools, with a few minor
readability cleanups and removals of some unused features around
vendored directories and deprecated workflow checks. Tests from
v-c-t are ported as well and some additional checks are added as
required.
Not ported here is the `IGNORE BAD COMMIT MESSAGES` override, which
will be added at a later date.

hgexports: add a commit message validation check to `DiffAssessor` (Bug 1902545)

---

landoapi/hgexports.py
tests/test_hgexports.py

Add a `check_wpt_sync` check to the `DiffAssessor` class which
is a port of the `prevent_wptsync_changes.py` hook in v-c-t.
The hook uses a regex to assert that the WPTSync bot user cannot
make changes to files outside of a specific directory in the main
tree. The bot is allowed to push any changes to `try`, but is
otherwise only allowed to make changes to files matching the regex.
Implement the `prevent_nspr_nss_changes.py` hook from v-c-t as a
check on the `DiffAssessor` API within Lando. The hook checks for
file changes under given directories in the tree and prevents updates
without a specific keyword in the commit message.

hgexports: port NSS/NSRP and WPTSync bot update prevention hooks as Lando checks (Bug 1903456)

---

landoapi/hgexports.py
tests/test_hgexports.py

Add a check to the `DiffAssessor` API that prevents introduction of
the `.gitmodules` file, which tracks Git submodules in the repository.

hgexports: add a check to prevent introducing Git submodules (Bug 1903462)

---

landoapi/celery.py
landoapi/cli.py
requirements.in
requirements.txt
tests/conftest.py

Due to a regression in newer Python build tools, our
currently installed version of `celery` fails to install
in the Docker image build as a result of improperly formatted
version specifiers. Install the latest version of `celery`
to resolve the issue, which also requires an update to
the `kombu` dependency. Updating `kombu` then causes a
regression in `redis`, so update `redis` to the latest
`3.x` version.
In newer versions of `celery` the pytest fixtures are disabled
by default, so add a `pytest_plugins` variable to the top-level
`conftest.py` to enable it.
Celery commands now fail when `sys.argv[0]` is passed as part
of `argv`, so remove them instead. The worker also requires the
`worker` command as the first argument, so update the call to
add it. We also add the broker URL as the …

requirements: update celery, redis and kombu (Bug 1904121)

---

landoapi/hg.py

Since `hg id <repo_url>` hits the network to connect to hgmo,
it can fail due to internal server errors and other connectivity
issues. In this case, we want the landing job to be retried in
the same fashion as when failing to pull/push. Map the exception
raised by `run_hg` to an `HgException` so the failure will be
considered a retry in the landing worker.

hg: convert errors from `hg id` to `HgException` (Bug 1908492)

---

landoapi/hgexports.py

Previously we had just removed the last two lines of output,
however if the patch has extra newlines this could fail and
cause the patch to be deformed. Use the helper function we
added to avoid issues with parsing the commit message.

git-patch-helper: use `strip_git_version_info_lines` when empty commit is found (Bug 1921023)

---

landoapi/hgexports.py
tests/test_hgexports.py

When parsing the Git patch sent through `git format-patch`, the
email parser returns escaped unicode. Explicitly set the charset
of the email to `utf-8` so the unescaped unicode string is returned.
Add a test which uses a real-life example of this issue, which fails
without specifying the charset but passes afterwards.

git-patch-helper: set charset to `utf-8` in email message parser (Bug 1893976)

---

landoapi/api/try_push.py
landoapi/bmo.py
landoapi/hgexports.py
landoapi/uplift.py
tests/test_hgexports.py
tests/test_try.py

Adds an API for push-wide checks and implements the bug references check
using it. The API defines a `PushCheck` interface which initializes the
check with a repo, defines a `relevant()` function which is called to
determine if the check should be run on the given repo, a `next_diff()`
function which accepts each diff parsed as a `PatchHelper`, and a
`result()` function which returns the error message for the check,
or `None` if the check passed.
The `BugReferencesCheck` is the first check to be implemented using this
new API. The check is only relevant on `try` repositories. Each diff is
passed via `next_diff`, and if `SKIP_BMO_CHECK` is found in the commit
message of any diff, a flag is set which indicates the check will be
skipped, otherwise the bug numbers found in the commit message …

checks: add a push-wide check API and implement bug references check (Bug 1915671)

---

landoapi/hg.py

`eslint` can make more than just formatting fixes, so we should disable it.

autoformat: remove `eslint` from supported formatters list (Bug 1924891)

---

landoapi/bmo.py

`headers` includes headers passed to the callers, which we add to the
`common_headers` dict to include things like the UA string and
API key. When we create the actual request, we are instead passing
the `headers` object and ignoring our common headers. Pass
`common_headers` to `requests.request` instead.

bmo: use `common_headers` instead of `headers` in requests (Bug 1925420)

---

landoapi/commit_message.py
tests/test_commit_message.py

Change `parse_bugs` to use `BUG_CONSERVATIVE_RE` to avoid incorrect parsing
of bug numbers during the `BugReferencesCheck`. Other code paths use the
`parse_bugs` function as well, but their tests pass after this change, so
we fully remove `BUG_RE` since it is no longer used.
Also remove the accidental double-definition of `BUG_RE` and `BUG_CONSERVATIVE_RE`
from `commit_message.py`.

commit_message: change `parse_bugs` to use `BUG_CONSERVATIVE_RE` (Bug 1926431)

---

tests/mocks.py

The `PhabricatorDouble` mock API calls take the `limit` parameter,
but do not actually limit the number of entries in the response data.
Add a check if `limit` is set and slice the `items `list at that index.

mocks: respect `limit` parameter in mock Conduit API endpoints (Bug 1927013)

---

landoapi/api/stacks.py
landoapi/api/transplants.py
landoapi/revisions.py
landoapi/stacks.py
landoapi/transplants.py
tests/mocks.py
tests/test_stacks.py
tests/test_transplants.py

Add a warning that checks when a revision has diffs from multiple
authors associated with it. First we add support to specify a diffs
author in the test suite. Then we update `request_extended_revision_data`
to pull diffs based on the `revisionPHID` instead of the diff `id`,
which returns all diffs for a given revision. We update
`gather_involved_phids` to take the list of diffs for a revision and
gather all diff authors as involved in the revision. We then add
the warning which gathers all the PHIDs that have authored diffs
on a revision, and emit a warning when there are multiple authors,
including the Phabricator username of each author.

checks: add a warning when a revision has diffs from multiple authors

---

landoapi/repos.py

- ci-admin was moved into ci-configuration.
- ci-configuration was moved to Github.
- taskgraph was moved to Github.
- fluent-migration was moved to Github.
- build-tools is deprecated.

repos: remove deprecated/moved repos from Lando (Bug 1925343)

---

landoapi/api/try_push.py
landoapi/hgexports.py
landoapi/transplants.py
tests/test_hgexports.py

This commit refactors the `DiffAssessor` API to more closely
match the `PatchCollectionCheck` API. A `PatchCheck` abstract
class is introduced which has a similar interface as the
`PatchCollectionCheck`, where each check can store state
as each part of the patch is iterated over using `next_diff`,
and `result()` is called to determine the final result of
the check. Each check in the `DiffAssessor` class is moved
to a class which subclasses `PatchCheck`.
To make the patch checks more closely resemble the patch
collection checks, each check to be run is passed as an
argument to `run_patch_collection_checks`, which allows
us to run the relevant checks based on the code path
or known relevant repository instead of unconditionally
running all checks. As a result, all logic around inspecting …

checks: refactor `DiffAssessor` check to more closely resemble `PatchCollectionCheck` (Bug 1932507)

---

landoapi/uplift.py
landoapi/workers/landing_worker.py

Currently when an uplift without a bug number hits the
Bugzilla update code path, an exception is thrown which
is turned into a failure email indicating Bugzilla could
not be updated. This commit changes the behaviour to
avoid trying to update Bugzilla if no bug numbers are
detected.

uplift: skip Bugzilla updates for landings without bugs (Bug 1934003)

---

landoapi/workers/landing_worker.py

Catch any exceptions thrown while setting reviewers from `mots.yaml`, so
they do not take down the landing worker and cause lag in the queue.

landing-worker: add a try/except block around `job.set_landed_reviewers` calls (Bug 1936373)

---

landoapi/workers/landing_worker.py

I used `logging.info` instead of `logger.info` in my haste, so this
logging message is not being sent to the proper location.

landing-worker: use `logger` instead of `logging` to log error (Bug 1936373)

---

landoapi/hgexports.py
tests/test_hgexports.py
tests/test_try.py

HgPatchHelper doesn't have this problem because it uses io.StringIO,
which yields the line endings.
Some tests need to be accommodated to the fact that the last line of a
diff now does contain newlines, which was accidentally not the case
before, and while doing that, adjust a little more test strings to be
more fitting with the reality that a patch will not terminate without
a newline at the end.

hgexports: fix CRLF handling in GitPatchHelper (bug 1944462)

---

landoapi/phabricator.py
tests/test_dockerflow.py
tests/test_phabricator_client.py

Some CDNs and WAFs block HTTP GET requests with bodies as security
measure. This patch changes the HTTP method to POST, which is spec
compliant. https://www.rfc-editor.org/rfc/rfc9110#name-get

phabricator: use POST method to be HTTP spec-compliant (Bug 1952541)

---

landoapi/api/landing_jobs.py
landoapi/spec/swagger.yml
tests/test_landing_job.py

When tools push to try, they only get the landing job id in return, while they often want the commit_id that TreeHerder uses. If the job isn't landed yet, a simple status is returned instead. Landed commit_id or job status isn't sensitive so an auth check isn't required.

api: Allow fetching landed commit_id of a landing job (bug 1954116)

---

landoapi/hg.py
landoapi/repos.py
tests/test_try.py

Switch to using `git cinnabar fetch` with the set of bookmarks to
retrieve, so we populate cinnabar metadata for all the relevant
revisions.

git: update cinnabar metadata with `git cinnabar fetch` (Bug 1965265)

---

Dockerfile-dev
landoapi/hg.py
landoapi/workers/landing_worker.py
tests/test_try.py

When converting the passed Git SHA to a Mercurial SHA, Lando-API
currently does nothing to assert the returned SHA is valid.
Add a check that the returned SHA is not the null SHA, and
raise a custom exception if it is. If a landing job hits this
exception, consider it a temporary failure and defer the job
until later.
In testing this patch I realized we do not install `git-cinnabar`
in the `Dockerfile-dev` file, so add that now to allow `git2hg`
to actually fail in the test.

cinnabar: check if `git2hg` returns the null SHA and defer jobs (Bug 1964576)
