landoapi/logging.py

Fix a typo in the default application log level name.

app: fix default log level

---

landoapi/phabricator.py

Add DEBUG logging to conduit API calls to aid local development.

logging: log conduit API calls

---

Dockerfile
landoapi/cli.py

Create base /repos directory for mounting, also fix get_subsystems
method to use subsystem instances for comparison.

Landings: create base repos directory in docker image

---

landoapi/landing_worker.py

- Load ssh keys from the environment variable
- Setup ssh agent for use in container

landing worker: add support for ssh

---

.flake8
.style.yapf
Dockerfile-dev
docker-compose.yml
landoapi/landing_worker.py
landoapi/repos.py

- adds config_override parameter to repos, to be used to add ssh options
- updates repo configs for local server and devsvcdev server
- clean up

development: fix support for dev ssh servers

---

landoapi/api/stacks.py

When a stack contains a bug that can't be queried by `differential.revision.search`, but is returned in a `edge.search` call, `build_stack_graph` raises an unhandled exception. This PR handles that exception.

stacks: catch exceptions when building stack graph (bug 1640190)

---

landoapi/landing_worker.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1651464.

landing worker: do not log every sleep cycle (bug 1651464)

---

landoapi/landing_worker.py

The environment variable needs to be set before entering the repo
context manager.

landing worker: fix AUTOLAND_REQUEST_USER (bug 1695315)

---

landoapi/hg.py
landoapi/landing_worker.py
landoapi/repos.py
tests/test_hg.py

- set and unset $AUTOLAND_REQUEST_USER in HgRepo context manager
- move string to own variable to reduce repetition/typos
- refactor context managers so that there is a separate one that will permit pushing to repo

landing worker: handle request user in context manager (bug 1695335)

---

landoapi/cli.py
landoapi/hooks.py
landoapi/landing_worker.py
landoapi/models/configuration.py
requirements.in
requirements.txt
tests/test_hooks.py
tests/test_landings.py
tests/test_revisions.py
tests/test_sanitized_commit_messages.py
tests/test_stacks.py
tests/test_transplants.py
tests/test_uplift.py

- add a maintenance mode `before_request` hook
- add a new configuration variable to control hook
- refactor pre/post deploy commands to include hook
- cache config value and invalidate when they are changed

hooks: add maintenance mode hook (bug 1715261)

---

requirements.in
requirements.txt

- requirements: remove `typing` module (Bug 1742720)
- requirements: update black to 21.11b1 (Bug 1742720)

requirements: remove typing and update black (Bug 1742720)

---

landoapi/api/stacks.py
landoapi/api/transplants.py
landoapi/commit_message.py
landoapi/phabricator.py
landoapi/repos.py
landoapi/reviews.py
landoapi/revisions.py
landoapi/transplants.py
landoapi/uplift.py
tests/conftest.py
tests/mocks.py
tests/test_commit_message.py
tests/test_reviews.py
tests/test_revisions.py
tests/test_sanitized_commit_messages.py
tests/test_stacks.py
tests/test_transplants.py
tests/test_uplift.py

This commit extends the existing uplift blocking check to include
checking for a submitted uplift request form somewhere on the
stack. The function name is updated to reflect the change.

Bug 1745293: amend release managers review check to check all required uplift conditions

---

landoapi/hg.py
landoapi/landing_worker.py
landoapi/treestatus.py
requirements.in
requirements.txt
tests/test_landings.py

- testing: add some assertion hints to test cases (Bug 1759890)
- typing: add type hints in a few places (Bug 1759890)
- testing: upgrade pytest to 7.1.1 (Bug 1754816)

meta: add type/assertion hints and upgrade pytest

---

landoapi/auth.py
landoapi/reviews.py
landoapi/transplants.py
landoapi/version.py

Add more type hints to function definitions in Lando. Also
remove the unused variable from `calculate_review_extra_state`.

typing: add more type hints to some functions (Bug 1759890)

---

landoapi/app.py
landoapi/auth.py
landoapi/cache.py
landoapi/cli.py
landoapi/commit_message.py
landoapi/hooks.py
landoapi/stacks.py
landoapi/ui.py

Also removed a few functions that are unused from `commit_message.py`.

typing: add type hints in a few files (Bug 1759890)

---

landoapi/phabricator.py

Add type hints everywhere in `phabricator.py`. While we're here,
we remove the unused `from_deprecated_id` function in `RevisionStatus`.
Also remove the unused `voidable` function from `ReviewerStatus`, which
allows us to remove `meta` by moving its remaining contents into
`diff_specific`.

phabricator: add type hints and remove some unused code (Bug 1759890)

---

requirements.in
requirements.txt

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1819115

requirements: update rs-parsepatch (bug 1819115)

---

landoapi/models/configuration.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1822080.

configuration: don't fetch previous value if initializing (bug 1822080)

---

landoapi/projects.py

- rename get_project_phid to get_or_set_project_phid
- move caching functionality to above method

projects: consolidate caching functionality (bug 1819319)

---

landoapi/workers/landing_worker.py

Refactor and simplify how exceptions are handling when pushing.

landing_worker: simplify exception handling when landing (bug 1823899)

---

landoapi/workers/landing_worker.py

Move merge conflict processing to its own function.

landing_worker: move merge conflict processing to function (bug 1823898)

---

requirements.in
requirements.txt

Each of the added requirements is used at least once in Lando's
core codebase.

requirements: pin requirements explicity in `requirements.in` (Bug 1824006)

---

landoapi/api/stacks.py
landoapi/models/revisions.py

- add Lando revision data to API response
- add serialize method to Revision class

stacks: add revision data to API response (bug 1835678)

---

landoapi/repos.py

Use `self.repos.items()` to get key/value tuples for
the repo list instead of re-creating it. Rename some
variable names to be more consistent and avoid using
single letter variables.

repos: do a small cleanup of the repo clone subsystem

---

landoapi/transplants.py
tests/test_transplants.py

After deploying the checks refactor, stacks with closed parents are
being shown as unable to land. In the old implementation of checks,
a subset of the checks applied to every revision in the stack, but
did not apply to the returned assessment. In the new implementation,
we are currently only running checks on the "relevant" revisions,
which means all revisions for regular stack checks and only the
landing path revisions for landing assessment checks. The latter
logic has the side-effect of not checking revisions outside of the
landing path, including the closed parents, which results in the
"valid landing path" check failing since it appears the passed
landing path is trying to land part of the stack without including
an open parent.
To resolve this, we first add two tests that reproduce …

checks: only block assessment when revision is in landing path (Bug 1897007)
